[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "14"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=365000000, immutable"
