name: Biome

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  biome:
    if: github.event.pull_request.draft == false
    name: Biome
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: biomejs/setup-biome@454fa0d884737805f48d7dc236c1761a0ac3cc13 # v2.6.0
        with:
          version: 2.2.3

      - run: biome check --reporter=github .
